# Generated by Django 3.0.3 on 2020-02-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
    ]
