# Generated by Django 3.0.3 on 2020-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='minimun_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
