# Generated by Django 3.0.3 on 2020-02-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('shop', '0008_auto_20200222_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
