# Generated by Django 3.0.3 on 2020-03-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productvariant_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='cost_price_amount',
            new_name='old_price',
        ),
    ]
