# Generated by Django 3.0.3 on 2020-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_digitalcontent_digitalcontenturl'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='downloads',
            field=models.ManyToManyField(to='shop.DigitalContent'),
        ),
    ]
