# Generated by Django 3.0.3 on 2020-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_digitalcontent_digitalcontenturl'),
        ('info', '0002_about_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='info.Contact'),
        ),
        migrations.AlterField(
            model_name='about',
            name='downloads',
            field=models.ManyToManyField(blank=True, to='shop.DigitalContent'),
        ),
        migrations.AlterField(
            model_name='about',
            name='team',
            field=models.ManyToManyField(blank=True, to='info.Member'),
        ),
    ]
