# Generated by Django 3.0.3 on 2020-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200304_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='about',
            name='other_refs',
            field=models.ManyToManyField(blank=True, to='info.OtherContacts'),
        ),
    ]
