# Generated by Django 3.0.3 on 2020-03-04 11:15

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200304_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products'),
        ),
    ]
