# Generated by Django 3.0.3 on 2020-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20200304_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='categories_heading',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
