# Generated by Django 3.0.3 on 2020-03-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebooksocial',
            old_name='url',
            new_name='handle',
        ),
        migrations.RenameField(
            model_name='instagramsocial',
            old_name='url',
            new_name='handle',
        ),
        migrations.RenameField(
            model_name='pinterestsocial',
            old_name='url',
            new_name='handle',
        ),
        migrations.RenameField(
            model_name='twittersocial',
            old_name='url',
            new_name='handle',
        ),
        migrations.RenameField(
            model_name='whatsappsocial',
            old_name='url',
            new_name='handle',
        ),
    ]
